# configuration: https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml
runtime: java
env: flex

runtime_config:
  jdk: openjdk8

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7

#liveness_check:
#  path: "/healthchecks/health"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#  initial_delay_sec: 300

#readiness_check:
#  path: "/healthchecks/ready"
#  check_interval_sec: 5
#  timeout_sec: 2
#  failure_threshold: 2
#  success_threshold: 2
#  app_start_timeout_sec: 300